# Generated by Django 4.0.6 on 2022-07-24 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_marks_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student',
        ),
        migrations.AddField(
            model_name='marks',
            name='rollno',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marks',
            name='std',
            field=models.CharField(choices=[('5', '5th'), ('6', '6th')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
